rootProject.name = "PluginLibrary"
include("core")
include("commands")
include("events")
include("reflect")
include("nbt")
include("inventories")
include("collections")
include("nbt-v1_17_R1")
include("math")
include("particles")
include("holograms")
include("titles")
